import { useState } from 'react'
import type { Expense } from '../types/expense'

type ExpenseFormProps = {
  // ID is now generated by the database, so we pass everything except id
  onAddExpense: (expense: Omit<Expense, 'id'>) => void
}

// const categories = [
//   'Food',
//   'Fuel',
//   'Rent',
//   'Bills',
//   'Shopping',
//   'Entertainment',
//   'Transport',
//   'Health',
//   'Other',
// ]

export function ExpenseForm({ onAddExpense }: ExpenseFormProps) {
const [date, setDate] = useState('')
const [amount, setAmount] = useState('')
const [category, setCategory] = useState('Food')
const [note, setNote] = useState('')

const handleSubmit = (event: React.FormEvent) => {
  event.preventDefault()

  const newExpense = {
    date,
    amount,
    category,
    note,
  }

  onAddExpense(newExpense)

  setDate('')
  setAmount('')
  setCategory('Food')
  setNote('')

}

// type ExpenseFormProps = {
//   date: string
//   amount: string
//   category: string
//   note: string
//   onDateChange: (value: string) => void
//   onAmountChange: (value: string) => void
//   onCategoryChange: (value: string) => void
//   onNoteChange: (value: string) => void
//   onAddExpense: (expense: Expense) => void
// }

// export function ExpenseForm({
//   date,
//   amount,
//   category,
//   note,
//   onDateChange,
//   onAmountChange,
//   onCategoryChange,
//   onNoteChange,
//   onAddExpense,
// }: ExpenseFormProps) {
  

return (
  <section className="card">
    <h2>Add Expense</h2>

    <form onSubmit={handleSubmit}>
      <input
        type="date"
        value={date}
        onChange={(event) => setDate(event.target.value)}
      />

      <input
        type="number"
        placeholder="Amount"
        value={amount}
        onChange={(event) => setAmount(event.target.value)}
      />

      <select
        value={category}
        onChange={(event) => setCategory(event.target.value)}
      >
        <option value="Food">Food</option>
        <option value="Transport">Transport</option>
        <option value="Bills">Bills</option>
        <option value="Other">Other</option>
      </select>

      <input
        type="text"
        placeholder="Note"
        value={note}
        onChange={(event) => setNote(event.target.value)}
      />

      <button type="submit">Add Expense</button>
    </form>
  </section>
)
}

